wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    huggingface_version: 4.22.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1663719989.071226
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.4
      5: 0.13.3
      6: 4.22.1
      8:
      - 5
batch_size:
  desc: null
  value: 16
edge_type:
  desc: null
  value: true
epochs:
  desc: null
  value: 120
layers_embeddings:
  desc: null
  value:
  - 128
  - 64
  - 32
learning_rate:
  desc: null
  value: 0.0003
mid_layer_dropout:
  desc: null
  value: 0.3
